@startuml
'https://plantuml.com/class-diagram
class DBService {
-SessionFactory sessionFactory
}

class UserDataSet {
-long id
-String email
-String password
}

class UserDao {
-Session session
}



class UserService

UserDao -> UserService

UserDataSet -> UserDao
DBService -> UserService

@enduml